---
# tasks file for ansible-role-rsyslog
- name: install rsyslog package
  yum:
    name:
      - rsyslog
  tags: rsyslog

- name: edit config (unlimited log burst)
  lineinfile:
    path: /etc/rsyslog.conf
    regexp: '^$SystemLogRateLimitInterval'
    insertbefore: '^#### GLOBAL DIRECTIVES ####'
    line: '$SystemLogRateLimitInterval 0'
  notify: restart rsyslog service
  tags: rsyslog

- block:
  - name: edit config (sender)
    lineinfile:
      path: /etc/rsyslog.conf
      regexp: '^.*\*\.\* @@'
      line: '*.* @@{{ rsyslog_recive_host }}:{{ rsyslog_listen_port }}'
    notify: restart rsyslog service
  - name: edit config (sender queue)
    replace:
      path: /etc/rsyslog.conf
      regexp: '^#(\$Action[Queue|Resume].*)$'
      replace: '\1'
    notify: restart rsyslog service
  when: not rsyslog_is_reciver and rsyslog_recive_host
  tags: rsyslog

- name: edit config (reciver)
  lineinfile:
    path: /etc/rsyslog.conf
    backrefs: yes
    regexp: '{{ item.regexp }}'
    line: '{{ item.line }}'
  with_items:
    - regexp: '^#(.*imtcp)$'
      line: '\1'
    - regexp: '^.*(\$InputTCPServerRun).*$'
      line: '\1 {{ rsyslog_listen_port }}'
  notify: restart rsyslog service
  when: rsyslog_is_reciver or rsyslog_test is defined
  tags: rsyslog

- name: copy recive log config
  template:
    src: recive_log.conf.j2
    dest: /etc/rsyslog.d/recive_log.conf
    mode: 0644
  notify: restart rsyslog service
  when: rsyslog_is_reciver or rsyslog_test is defined
  tags: rsyslog

- name: start rsyslog service
  service:
    name: rsyslog
    state: started
    enabled: yes
  tags: rsyslog
