---
# tasks file for ansible-role-rsyslog
- name: install rsyslog package
  yum:
    name:
      - rsyslog

- name: edit config (unlimited log burst)
  lineinfile:
    path: /etc/rsyslog.conf
    regexp: '^$SystemLogRateLimitInterval'
    insertbefore: '^#### GLOBAL DIRECTIVES ####'
    line: '$SystemLogRateLimitInterval 0'
  notify: restart rsyslog service

- name: edit config (sender)
  blockinfile:
    path: /etc/rsyslog.conf
    insertbefore: '^# ### end of the forwarding rule ###'
    block: |
      $ActionQueueFileName fwdRule{{ item.0 }}
      $ActionQueueMaxDiskSpace 1g
      $ActionQueueSaveOnShutdown on
      $ActionQueueType LinkedList
      $ActionResumeRetryCount -1
      *.* @@{{ hostvars[item.1]['ansible_host'] if hostvars[item.1] is defined else item.1 }}:{{ rsyslog_reciver_listen_port }}
    marker: '# {mark} ANSIBLE MANAGED BLOCK {{ item.0 }}'
  with_indexed_items: '{{ rsyslog_reciver_hostnames }}'
  notify: restart rsyslog service
  when: rsyslog_reciver_hostnames != None

- name: edit config (reciver)
  lineinfile:
    path: /etc/rsyslog.conf
    backrefs: yes
    regexp: '{{ item.regexp }}'
    line: '{{ item.line }}'
  with_items:
    - regexp: '^#(.*imtcp)$'
      line: '\1'
    - regexp: '^.*(\$InputTCPServerRun).*$'
      line: '\1 {{ rsyslog_reciver_listen_port }}'
  notify: restart rsyslog service
  when: rsyslog_reciver_hostnames != None and inventory_hostname in rsyslog_reciver_hostnames or rsyslog_test is defined

- name: copy recive log config
  template:
    src: recive_log.conf.j2
    dest: /etc/rsyslog.d/recive_log.conf
    mode: 0644
  notify: restart rsyslog service
  when: rsyslog_reciver_hostnames != None and inventory_hostname in rsyslog_reciver_hostnames or rsyslog_test is defined

- name: start rsyslog service
  service:
    name: rsyslog
    state: started
    enabled: yes
